const Rover = require('../rover.js');
const Message = require('../message.js');
const Command = require('../command.js');

// This file is for grading tests. Please do not edit this file for any reason.

describe("GRADING TEST: ", function() {

   it("Responds to TA message & commands", function() {
    let rover = new Rover(100);
   let commands = [
      new Command('MOVE', 4321),
      new Command('STATUS_CHECK'),
      new Command('MODE_CHANGE', 'LOW_POWER'),
      new Command('MOVE', 3579),
      new Command('STATUS_CHECK')
   ];
   //  let rover = new Rover(100);
    let message = new Message('TA power', commands);
    let response = rover.receiveMessage(message);
     expect(response[0].message).toEqual('TA power');
     expect(response[1].completed).toBeTruthy();
     expect(response[2][0].roverStatus.position).toEqual(4321);
     expect(response[3].completed).toBeTruthy();
     expect(response[4].completed).toBeFalsy();
     expect(response[5][0].roverStatus.position).toEqual(4321);
     expect(response[5][0].roverStatus.mode).toEqual('LOW_POWER');
     expect(response[5][0].roverStatus.generatorWatts).toEqual(110);
   });

});
